### PR TITLE
fix: fix sort for all catalog table entities (#663)

### LINKED ISSUE #663: Fix sort for all catalog table entities
- Refactor table sort to use React Table sort API
- Fix table sort for all catalog entities

### PR DESCRIPTION
**Pull request by frano-m**
### Ticket
Closes #663.

### Reviewers
@NoopDog 

### Changes
- Updated React Table to use React Table sorting API so all table entities are sortable.
- Modified sort in explorer state to align with React Table sorting API.

### Definition of Done (from ticket)
- All table entities are sortable.

### CODE REVIEW

File: explorer/app/common/context/exploreState.tsx [hunk 1]
```diff
@@ -163,31 +162,29 @@ export type ExploreState = {
   loading: boolean;
   paginationState: PaginationState;
   relatedListItems: RelatedListItems;
-  sortState: ColumnSort | undefined; // TODO update sortState to ColumnSort[]?
+  sorting: ColumnSort[];
```
Comment (frano-m) [inline explorer/app/common/context/exploreState.tsx:165]: Updated `sorting` to always be defined - if the configuration "default" is undefined, we return an empty array. This is to support future use of `resetSorting` functions.

File: explorer/app/components/Table/common/utils.ts [hunk 2]
```diff
@@ -99,23 +101,26 @@ export function getColumnSortDirection(
...
           checked: getIsVisible(),
           disabled: initialVisibilityState[id],
           label: header as string, // TODO revisit type assertion here
-          onChange: (event: ChangeEvent<HTMLInputElement>): void => {
-            setColumnVisibility({
-              ...columnVisibility,
-              [id]: event.target.checked,
-            });
-          },
+          onChange: getToggleVisibilityHandler(),
```
Comment (frano-m) [inline explorer/app/components/Table/common/utils.ts:123]: Updated the column visibility `onChange` function to match the same API as column sort `onChange` function.

File: explorer/app/components/Table/table.tsx [hunk 3]
```diff
@@ -84,10 +84,15 @@ export const TableComponent = <T extends object>({
     listStaticLoad,
     paginationState,
     relatedListItems,
-    sortState,
+    sorting,
   } = exploreState;
   const { currentPage, pages, pageSize, rows } = paginationState;
-  const sorting = sortState ? [sortState] : undefined;
+  const onSortingChange = (updater: Updater<ColumnSort[]>): void => {
```
Comment (frano-m) [inline explorer/app/components/Table/table.tsx:90]: `onSortingChange` payload needs to be able to type check `updater` - the `resetSorting` API returns `updater` as a value.

**Review by NoopDog — APPROVED** [review]
