### PR TITLE
Fix Loading component. #491.

### LINKED ISSUE #491: Fix Loading component
The loading component throw an error when going to `/explore/export/export-to-terra` directly.
The loading component zIndex is too high and covers an open filter menu.

Image

Definition Of Done
- The loading component renders below an open filter menu.
- The loading component does not throw an error when going to `/explore/export/export-to-terra` directly.

### PR DESCRIPTION
**Pull request by frano-m**
### Ticket
Closes #491.

### Reviewers
@MillenniumFalconMechanic.

### Changes
- Removed `RoundedLoading` styles and modified Loading component to take a prop that defines the loading style.
- Updated Loading zIndex.
- Updated SB.

### Definition of Done (from ticket)
- Loading component renders underneath an open filter menu.
- Loading component does not throw an error when going to `/explore/export/export-to-terra` directly.

### CODE REVIEW

File: explorer/app/components/Loading/loading.tsx [hunk 1]
```diff
@@ -6,18 +6,19 @@
...
-  className?: string;
   loading: boolean;
+  panelStyle?: PaperPanelStyle; // Enables loading to mirror parent container styles.
   text?: string;
 }
 
 export const Loading = ({
-  className,
   loading,
-  text = "Your link will be ready shortly...",
```
Comment (frano-m) [inline explorer/app/components/Loading/loading.tsx:20]: Removed the assignment of "Your link..." when text is undefined for the benefit of using the Loading component on the Index table.

**Review by NoopDog — APPROVED** [review]
