### PR TITLE
Prop drilling isLoading to table + fixes. #261

### LINKED ISSUE #261: Prevent page refresh on pagination
#### Need
We would like to be able to paginate through the entity lists with only the list component refreshing rather than the entire page.

#### Definition of Done
* Only list component (or similar) is refreshed during pagination.
* Header, tabs etc are not re-rendered.

### LINKED ISSUE #262: Prevent page refresh on sort
#### Need
We would like to be able to sort entity lists with only the list component refreshing rather than the entire page.

#### Definition of Done
* Only list component (or similar) is refreshed on sort of entity list column.
* Header, tabs etc are not re-rendered.

### PR DESCRIPTION
**Pull request by BruceRodrigues**
### Ticket
Closes #261 
Closes #262 

### Reviewers
@.

### Changes
- Prop drilling isLoading to table

### Known Issues
It was created a loading state for table, that for now it only shows "Loading...".
I've noticed an error where, on changing the entity tab, the default sort wasn't being applied. (This PR will fix it)

### CODE REVIEW

File: explorer/app/hooks/useFetchEntities.ts [hunk 1]
```diff
@@ -65,10 +63,11 @@ export const useFetchEntities = (value?: ListModel): UseEntityListResponse => {
     data: apiData,
     isLoading: apiIsLoading,
     run,
+    isIdle,
   } = useAsync<ListResponseType>();
 
   useEffect(() => {
-    if ((!staticLoad || isDevelopment()) && !isSSR()) {
```
Comment (BruceRodrigues) [inline explorer/app/hooks/useFetchEntities.ts:71]: A lot has changed since this check was created, and I noticed that it doesn't seem to make sense anymore. So I tried removing it and tested every config (I'm having some issues with anvil and hca's API, so could do the complete test for these configs, but it's working for all the others.)

File: explorer/app/components/Table/table.tsx [hunk 2]
```diff
@@ -111,6 +116,18 @@ export const Table = <T extends object>({
     }
   };
 
+  const handleTableNextPage = (): void => {
+    const nextPage = pagination?.nextPage ?? tableNextPage;
+    nextPage();
+    scrollTop();
```
Comment (BruceRodrigues) [inline explorer/app/components/Table/table.tsx:122]: I'm scrolling to page top when pagination changes

File: explorer/app/components/Table/table.tsx [hunk 3]
```diff
@@ -71,6 +74,7 @@ export const Table = <T extends object>({
   pagination,
   sort,
   total,
+  isLoading,
```
Comment (MillenniumFalconMechanic) [inline explorer/app/components/Table/table.tsx:77]: Would it be possible to rename this to `loading`, here and throughout the prop drilling? I would like to try to standardize booleans to the following Java-style (to maintain consistency across our projects):

Field name: `loading`
Accessor: `isLoading()`
Mutator: `setLoading(loading: boolean)`

Don't worry about other `isX` values for now (e.g. `isIdle`); we can address that in a separate PR!

File: explorer/app/components/Table/table.tsx [hunk 4]
```diff
@@ -164,8 +181,8 @@ export const Table = <T extends object>({
                   {row.cells.map((cell, index) => {
                     return (
                       <TableCell {...cell.getCellProps()} key={index}>
-                        {cell.render("Cell")}
-                      </TableCell>
+                        {isLoading ? "Loading..." : cell.render("Cell")}
```
Comment (MillenniumFalconMechanic) [inline explorer/app/components/Table/table.tsx:184]: Would you be able to move the `isLoading` check higher and also just show `<></>` for now if loading? Our mock for the loading state is currently table-wide (see [mocks](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=358%3A7778)).

Comment (MillenniumFalconMechanic) [reply explorer/app/components/Table/table.tsx:184]: Keep its companion `// TODO` close to where you move the `isLoading` check!

**Review by MillenniumFalconMechanic — CHANGES_REQUESTED** [review]
Looks good Bruce, thank you! Just a few nits for when you have a moment.

File: explorer/app/hooks/useFetchEntities.ts (hunk 1 above)
Comment (MillenniumFalconMechanic) [reply explorer/app/hooks/useFetchEntities.ts:71]: Thank you!

File: explorer/app/components/Table/table.tsx (hunk 4 above)
Comment (BruceRodrigues) [reply explorer/app/components/Table/table.tsx]: From the mocks, I noticed that we'll still render the table when loading, so I'm not returning `<></>` when loading. I'm presenting a `<span>Loading...</span>` instead.
I'm assuming we'll have a container div with `position: relative` and the loading component as a table sibling with `position: absolute`.
Is that ok?

**Review by MillenniumFalconMechanic — APPROVED** [review]
LGTM, thanks Bruce!
