### PR TITLE
Images issue #204

### LINKED ISSUE #204: Image issues with basePath
Images with data URLs are broken as they have basepath appended to the data. This must have come in with the new basepath changes. Looks like  

export const BASE_PATH = "/explore/";

in staticImage.tsx may be causing this?

image

image

Also...

When building,  images have an extra / appended explore and look like:
image

This looks like it's caused by the trailing / in the BASE_PATH above.

Finally,

Is there a way to avoid declaring the BASE_PATH in the file? Basepath may change and it would be nice to specify this in one place. 

image

Thanks,
D

### PR DESCRIPTION
**Pull request by BruceRodrigues**
closes #204 

### Changes
- using router to get BasePath

### CODE REVIEW

File: explorer/app/components/common/StaticImage/staticImage.tsx [hunk 1]
```diff
@@ -27,8 +23,13 @@ export const StaticImage = ({
   src,
   width,
 }: StaticImageProps): JSX.Element => {
-  return (
-    <img alt={alt} height={height} src={`${BASE_PATH}${src}`} width={width} />
-  );
+  const router = useRouter();
+
+  // If src is a image in base64, don't add the basePath
+  const srcValue = src?.startsWith("data:image/")
```
Comment (BruceRodrigues) [inline explorer/app/components/common/StaticImage/staticImage.tsx:29]: Nih svg image is the only one that has the src as a base64 image. I have no idea why. Try to convert it into different formats but didn't work. So I'm just addressing base64 images here

Comment (NoopDog) [reply explorer/app/components/common/StaticImage/staticImage.tsx:29]: Yes, there are a few others. I think it does this to small ones on the build.

**Review by NoopDog — APPROVED** [review]
