### PR TITLE
Export to terra page + fixes. #394

### LINKED ISSUE #394: Display export to Terra page
#### Need
Once a user has selected to the "export data to Terra" export method, we need to display a page with an export options form and a button to initiate the export. See [mocks](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/explore-dashboard?node-id=1012%3A19397).

#### Approach
* For now, let's go with a "hard-coded" approach rather than a configurable approach for the export. We will address converting the export to a configurable model in a separate ticket.
* Add a new route (and page) at `/export/export-to-terra`.  
* Add a new `ExportToTerra` view that re-uses the existing `BackPageView` functionality.
* The main column will eventually contain a single `ExportToTerra` component. The `ExportToTerra` component is currently [in progress](https://github.com/clevercanary/data-browser/issues/461) so for now just add a div with the text "to do".
* The side column displays a single data use policy component (see example on choose export page).
* Update Terra export method `route` to point to Terra export (i.e. `/export/export-to-terra`).

### PR DESCRIPTION
**Pull request by BruceRodrigues**
### Ticket
Closes #394 

### Reviewers
@.

### Changes
- Adding ExportToTerra page with hardcoded data.
- Fixing breadcrumb link to export page

### CODE REVIEW

File: explorer/app/viewModelBuilders/azul/hca-dcp/common/viewModelBuilders.ts [hunk 1]
```diff
@@ -31,7 +31,7 @@ export const buildExportToTerraMetadata = (): React.ComponentProps<
   description:
     "Terra is a biomedical research platform to analyze data using workflows, Jupyter Notebooks, RStudio, and Galaxy.",
   disabled: false,
-  route: "/export",
+  route: "/export/export-to-terra",
```
Comment (MillenniumFalconMechanic) [inline explorer/app/viewModelBuilders/azul/hca-dcp/common/viewModelBuilders.ts:34]: Good catch!

**Review by MillenniumFalconMechanic — APPROVED** [review]
LGTM, thanks Bruce!
